Coipeault\CN\CoipeaultCMSBundle\Document\Page:
    uri_schema: /page/{title}
    token_providers:
        title:  [content_method, { method: getTitle }]
        
Coipeault\CN\CoipeaultCMSBundle\Document\BlogPost:
    uri_schema: /page/{date}/{title}
    token_providers:
        date:   [content_datetime, { method: getDate }]
        title:  [content_method, { method: getTitle }]
